const whatsapp = 'https://wa.me/5551981555601?text=' + encodeURIComponent('Olá, quero conversar sobre meu posicionamento e entender se o Mapa de Posicionamento faz sentido para o meu momento.');
const routePaths = {
  '/': '/',
  '/sites-estrategicos': '/sites-estrategicos/',
  '/como-funciona': '/como-funciona/',
  '/sobre': '/sobre/',
  '/contato': '/contato/'
};
const method = [['01','Escutar','Começamos entendendo o momento do negócio, o trabalho e o que hoje pede clareza.'],['02','Reconhecer','Identificamos aquilo que já tem valor, consistência e pode sustentar a sua autoridade.'],['03','Destravar','Organizamos decisões e padrões que deixam a mensagem, a oferta ou a presença dispersas.'],['04','Traduzir','Transformamos o que foi reconhecido em posicionamento, linguagem e direção.'],['05','Construir','Damos forma à presença digital com estratégia, conteúdo e uma experiência clara.'],['06','Sustentar','Deixamos uma base que acompanha o crescimento e permite evoluir com coerência.']];
const methodIcons = {
  '01':'<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M9 24h5m5-8h4m-4 16h4m7-16c4 3 4 13 0 16m7-22c8 7 8 21 0 28"/><path d="M24 12v24"/></svg>',
  '02':'<svg viewBox="0 0 48 48" aria-hidden="true"><circle cx="24" cy="24" r="7"/><path d="M24 7v5m0 24v5M7 24h5m24 0h5M12 12l4 4m16 16 4 4m0-24-4 4M16 32l-4 4"/></svg>',
  '03':'<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M9 16h15m0 0-5-5m5 5-5 5M39 32H24m0 0 5-5m-5 5 5 5"/><path d="M35 10v28"/></svg>',
  '04':'<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M10 14h12v12H10zM26 22h12v12H26z"/><path d="M22 20h7m-3-4 4 4-4 4"/></svg>',
  '05':'<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M10 34h28M14 28h20M18 22h12M22 16h4"/><path d="M10 38h28"/></svg>',
  '06':'<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M10 34h28M14 28h20M18 22h12"/><path d="M24 8v12m-5-5 5 5 5-5"/></svg>'
};
const methodGroups = [
  ['01','ENTENDER','Escutar e reconhecer','Primeiro, entendemos o momento do negócio e identificamos aquilo que já tem valor e consistência.',['01','02']],
  ['02','ORGANIZAR','Destravar e traduzir','Depois, organizamos as decisões dispersas e transformamos esse entendimento em posicionamento, linguagem e direção.',['03','04']],
  ['03','DAR FORMA','Construir e sustentar','Por fim, damos forma à presença digital e deixamos uma base que pode acompanhar a evolução do negócio.',['05','06']]
];
const cta = (label='Conversar sobre meu posicionamento') => `<a class="button" data-wa href="${whatsapp}">${label}<span aria-hidden="true">↗</span></a>`;
const imageMeta = {
  'hero-novo.jpeg': [2048, 2048],
  'site-estrategico-novo.jpeg': [1792, 2400],
  'organizacao-do-caos-a-clareza-v1.png': [1122, 1402],
  'edson-novo.jpeg': [1792, 2400],
  'cta-novo.jpeg': [2752, 1536]
};
const image = (name, alt, className='section-image') => {
  const [width, height] = imageMeta[name];
  const isHero = className === 'hero-image';
  return `<figure class="section-image ${className}"><img src="/images/${name}" alt="${alt}" width="${width}" height="${height}" loading="${isHero ? 'eager' : 'lazy'}" decoding="async"${isHero ? ' fetchpriority="high"' : ''}></figure>`;
};
const intro = (eyebrow,title,text) => `<section class="page-intro"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lead">${text}</p>${cta()}</div><div class="intro-mark" aria-hidden="true"><i></i><i></i><i></i></div></section>`;
const homePage = () => `<section class="hero"><div class="hero-copy"><p class="eyebrow">CLAREZA DE POSICIONAMENTO PARA PROFISSIONAIS LIBERAIS</p><h1>O seu negócio já tem valor.<br><em>Falta deixar claro</em> por que as pessoas certas deveriam escolher você.</h1><p class="lead">Você pode ter experiência, dominar diferentes áreas e entregar um excelente trabalho — e ainda ser percebido como apenas mais uma opção. A Crie SeUniverso transforma esse repertório em foco, oferta, linguagem e materiais que o cliente consegue compreender, valorizar e contratar. Começamos pelo Mapa de Posicionamento e damos forma a essa direção em um Site Estratégico próprio.</p><div class="actions">${cta()}<a class="text-link" href="/como-funciona/">Conhecer o processo <span>↓</span></a></div><p class="microcopy">Você não precisa chegar com tudo definido. Pesquisamos, organizamos e construímos essa direção junto com você.</p></div><aside class="hero-side">${image('hero-novo.jpeg','Edson Lima em ambiente profissional','hero-image')}<div class="hero-architecture"><p>clareza que se torna <strong>escolha.</strong></p><div class="architecture"><b>quem conduz</b><span></span><b>modelo de negócio</b><span></span><b>posicionamento</b><span></span><b>site estratégico</b></div></div></aside></section>
  <section class="section problem"><div class="number">01</div><div><p class="eyebrow">O PROBLEMA NÃO É FALTA DE COMPETÊNCIA</p><h2>Você sabe fazer muita coisa. O cliente só não consegue entender por onde começar.</h2><p>Talvez você tenha acumulado formações, experiências e diferentes maneiras de ajudar. Mas, quando todas aparecem com o mesmo peso, o cliente encontra uma lista de possibilidades — não uma razão clara para escolher você.</p><ul class="checklist"><li>Cada conversa começa com uma longa explicação.</li><li>Seus serviços parecem desconectados uns dos outros.</li><li>O cliente não entende qual solução responde ao problema dele.</li><li>A comunicação atrai curiosidade, mas não facilita a contratação.</li></ul><p>Você pode saber muito sobre a sua profissão e ainda não ser reconhecido por uma proposta específica.</p></div></section>
  <section class="statement"><p class="eyebrow">FOCO NÃO É LIMITAÇÃO</p><h2>Escolher o que será reconhecido primeiro não apaga o restante do seu repertório.</h2><p>Posicionamento não obriga você a abandonar conhecimentos, formações ou possibilidades de atendimento. Ele cria uma porta de entrada para que o cliente consiga compreender o seu trabalho.</p><p>Em vez de apresentar tudo para todos, organizamos qual problema merece ocupar o centro da comunicação, quem percebe esse problema com mais intensidade e como suas habilidades podem ser combinadas em uma solução coerente.</p></section>
  <section class="section method"><div class="number">02</div><div><p class="eyebrow">O PONTO DE PARTIDA</p><h2>Mapa de Posicionamento: direção para transformar experiência em uma oferta que faça sentido.</h2><p>O Mapa de Posicionamento organiza o que o seu negócio faz, para quem faz, por que vale a pena escolher você e como isso precisa ser explicado.</p><div class="method-journey"><article class="journey-step"><div class="journey-heading"><small>01</small><span>ENCONTRAR O FOCO</span></div><h3>Uma porta de entrada para o seu repertório.</h3><p>Pesquisamos o nicho, compreendemos o cliente de melhor ajuste, identificamos a dor prioritária e escolhemos o foco mais forte para começar.</p></article><article class="journey-step"><div class="journey-heading"><small>02</small><span>ORGANIZAR A OFERTA</span></div><h3>Serviços e pacotes com lógica.</h3><p>Transformamos habilidades, serviços e técnicas em soluções com explicação, materiais e uma forma de entrega coerente.</p></article><article class="journey-step"><div class="journey-heading"><small>03</small><span>DAR FORMA À ESCOLHA</span></div><h3>Uma mensagem que o cliente reconhece.</h3><p>Construímos a comunicação e o Site Estratégico para que a pessoa certa encontre, compreenda, confie e avance para uma conversa.</p></article></div>${cta('Quero entender o Mapa de Posicionamento')}</div></section>
  <section class="section deliverables"><div class="number">03</div><div><p class="eyebrow">A ESTRATÉGIA VIRA MATERIAL DE TRABALHO</p><h2>Você não recebe apenas recomendações. Recebe uma base que pode ser colocada em prática.</h2><p>De acordo com o momento e a necessidade do seu negócio, o Mapa pode organizar:</p><ul class="checklist"><li>Arquitetura de posicionamento, pesquisa de nicho e dor prioritária.</li><li>Público de melhor ajuste, foco de entrada e explicação comercial.</li><li>Serviços, atendimentos e pacotes conforme as suas habilidades reais.</li><li>Fichas, relatórios, propostas e materiais relacionados à experiência de atendimento.</li><li>Direção para o Site Estratégico, que materializa o posicionamento em canal próprio.</li></ul><p>Materiais e processos que envolvem dados de clientes podem ser organizados com orientação jurídica especializada para apoiar sua adequação à LGPD.</p><p><strong>Resultado:</strong> confiança para oferecer algo que possa ser explicado e tangibilizado.</p></div></section>
  <section class="offer"><div><p class="eyebrow">O SEU ENDEREÇO PRÓPRIO NA INTERNET</p><h2>As redes sociais são estradas. O Site Estratégico é o seu endereço próprio.</h2><p>Instagram, Facebook, LinkedIn e outras plataformas ajudam as pessoas a chegar até você. Mas algoritmos, regras, bloqueios e mudanças nessas redes não estão sob o seu controle.</p><p>O Site Estratégico concentra sua mensagem, apresenta sua oferta e organiza o caminho de quem deseja conhecer e contratar o seu trabalho.</p>${cta('Conhecer o Site Estratégico')}</div>${image('site-estrategico-novo.jpeg','Edson Lima explicando conceitos e organizando um quadro de trabalho','offer-image')}<ul><li>Entender o que você faz sem depender de uma longa explicação</li><li>Reconhecer se a solução foi pensada para ele</li><li>Compreender seus diferenciais e suas ofertas</li><li>Encontrar um próximo passo claro para conversar</li><li>Ter um canal próprio que pode evoluir com o negócio</li></ul></section>
  <section class="statement"><p class="eyebrow">MATURIDADE DE NEGÓCIO</p><h2>Estratégia com a maturidade de quem conhece um negócio por dentro.</h2><p>A Crie SeUniverso é conduzida por Edson Lima, com mais de 25 anos de experiência em gestão, vendas, atendimento, equipes e negócios de diferentes segmentos.</p><p>A esse repertório somam-se cinco anos de atuação direta com terapias integrativas. Essa experiência ajuda a compreender profissionais que acumulam diferentes formações e precisam transformá-las em uma proposta responsável, coerente e comercialmente explicável.</p></section>
  <section class="section audience"><div class="number">04</div><div><p class="eyebrow">PROFISSIONAIS LIBERAIS</p><h2>Para quem entrega um bom trabalho, mas ainda não é reconhecido por uma proposta específica.</h2><p>O processo foi pensado para terapeutas, advogados, consultores, arquitetos e outros profissionais liberais que possuem experiência real, mas sentem dificuldade para organizar tudo o que sabem em uma oferta compreensível.</p><p>Você não precisa chegar com nicho, pacote, textos ou todas as respostas definidos. Organizar essas decisões faz parte do trabalho.</p></div></section>
  ${finalCta()}`;
const pages = {
  '/': () => `<section class="hero"><div class="hero-copy"><p class="eyebrow">ARQUITETURA DE POSICIONAMENTO E PRESENÇA DIGITAL</p><h1>O seu negócio já tem valor.<br><em>Falta uma presença</em> que faça isso ser percebido.</h1><p class="lead">Você pode fazer um trabalho profundo, consistente — e ainda ver as pessoas chegarem sem entender direito por que escolher você. A Crie SeUniverso organiza a experiência, a oferta e os diferenciais que já existem no seu negócio em um posicionamento claro e um Site Estratégico que ajuda as pessoas certas a compreender, confiar e iniciar uma conversa.</p><div class="actions">${cta('Entender se o Site Estratégico faz sentido agora')}<a class="text-link" href="/como-funciona/">Entender como funciona <span>↓</span></a></div><p class="microcopy">Você não precisa chegar com tudo decidido. A primeira conversa começa pelo que o seu negócio já tem.</p></div><aside class="hero-side">${image('hero-novo.jpeg','Edson Lima em ambiente profissional','hero-image')}<div class="hero-architecture"><p>clareza que se torna <strong>presença.</strong></p><div class="architecture"><b>quem conduz</b><span></span><b>modelo de negócio</b><span></span><b>posicionamento</b><span></span><b>presença digital</b></div></div></aside></section>
  <section class="section problem"><div class="number">01</div><div><p class="eyebrow">O QUE PODE ESTAR ACONTECENDO</p><h2>Você explica, posta, responde — e cada pessoa entende uma coisa diferente.</h2><p>Um Instagram ativo, um site feito apenas para estar no ar ou uma comunicação construída por partes podem até gerar presença. Mas raramente organizam a compreensão de quem chega. Às vezes, o trabalho é consistente e a experiência é real. O que falta não é mais conteúdo: é uma forma clara de fazer tudo isso ser percebido.</p></div></section>
  <section class="statement"><p class="eyebrow">UM PONTO DE VISTA</p><h2>O seu negócio não precisa parecer maior do que é.<br><em>Precisa mostrar o valor que já construiu.</em></h2><p>Posicionamento não é inventar uma versão mais bonita da sua história. É encontrar palavras, decisões e uma presença capazes de sustentar quem você já é no trabalho.</p></section>
  <section class="section method"><div class="number">02</div><div><p class="eyebrow">O MÉTODO</p><h2>Antes de qualquer página, entendemos o que o seu trabalho precisa tornar claro.</h2><div class="method-journey">${methodGroups.map(g=>`<article class="journey-step"><div class="journey-heading"><small>${g[0]}</small><span>${g[1]}</span></div><h3>${g[2]}</h3><p>${g[3]}</p><div class="journey-pairs">${g[4].map(id=>{const x=method.find(m=>m[0]===id);return `<div><span class="method-icon">${methodIcons[id]}</span><b>${x[1]}</b><p>${x[2]}</p></div>`}).join('')}</div></article>`).join('')}</div></div></section>
  <section class="offer"><div><p class="eyebrow">SITE ESTRATÉGICO</p><h2>Um site é a forma visível de uma decisão maior.</h2><p>Um Site Estratégico é o lugar onde alguém consegue entender o seu trabalho sem depender de uma longa explicação sua. Antes do layout, organizamos quem você atende, que situação ajuda a transformar, o que diferencia sua forma de trabalhar e qual deve ser o próximo passo para quem chega.</p>${cta('Conhecer o Site Estratégico')}</div>${image('site-estrategico-novo.jpeg','Edson Lima explicando conceitos e organizando um quadro de trabalho','offer-image')}<ul><li>Para não precisar explicar tudo do zero a cada contato</li><li>Para sua autoridade fazer sentido para quem ainda não conhece seu trabalho</li><li>Para a pessoa certa reconhecer que encontrou o que procura</li><li>Para a sua presença ir além do Instagram</li><li>Para evoluir sem recomeçar a comunicação toda vez</li></ul></section>
  <section class="section audience"><div class="number">03</div><div><p class="eyebrow">PARA QUEM É</p><h2>Para quem entrega um bom trabalho, mas sente que a presença ainda não acompanha.</h2><p>Profissionais liberais, especialistas independentes, negócios locais e pequenos escritórios que já têm competência real — e desejam ser encontrados, compreendidos e escolhidos com mais clareza.</p></div></section>
  ${finalCta()}`,
  '/sites-estrategicos': () => intro('SITE ESTRATÉGICO','Uma presença que torna seu valor mais fácil de reconhecer.','Você não precisa chegar com tudo pronto. O Site Estratégico começa entendendo o que já existe no seu trabalho e organizando isso para que as pessoas certas consigam compreender por que escolher você.') + `<section class="section organizing-section"><div class="organizing-copy"><p class="eyebrow">O QUE ELE ORGANIZA</p><h2>Mais do que páginas, um caminho de entendimento.</h2><p>Antes de escolher cores, layouts ou palavras bonitas, organizamos o essencial: quem você atende, que situação ajuda a transformar, o que diferencia sua forma de trabalhar e qual caminho a pessoa deve seguir para conversar com você.</p><ul class="checklist"><li>Uma oferta que pode ser explicada com clareza</li><li>Uma mensagem que dá contexto à sua autoridade</li><li>Uma experiência que ajuda a pessoa certa a se reconhecer</li><li>Um caminho simples para iniciar uma conversa</li><li>Uma base digital que pode evoluir com o negócio</li></ul></div>${image('organizacao-do-caos-a-clareza-v1.png','Elementos dispersos conectados até uma presença digital organizada','organization-diagram')}</section><section class="section fit-section"><div class="number">02</div><div><p class="eyebrow">ANTES DE COMEÇAR</p><h2>Você não precisa ter tudo pronto para conversar.</h2><p>Não é necessário chegar com marca final, textos fechados ou todas as respostas. A primeira conversa serve para olhar o momento do negócio, entender o que já tem consistência e avaliar se este é o momento certo para organizar isso.</p><p>O Site Estratégico faz sentido quando existe um trabalho real e a vontade de torná-lo mais claro para quem precisa reconhecê-lo.</p></div></section>${finalCta()}`,
  '/como-funciona': () => intro('COMO FUNCIONA','Um processo para dar forma ao que já existe.','Você não precisa chegar com a história pronta ou com todas as respostas. A jornada começa pelo seu momento e transforma experiência, decisões e direção em uma presença que as pessoas conseguem compreender.') + `<section class="section method-page-intro"><div class="number">01</div><div><p class="eyebrow">UM CAMINHO, NÃO UMA FÓRMULA</p><h2>Não começamos perguntando qual cor você prefere.</h2><p>Começamos entendendo o que o seu trabalho precisa tornar claro para quem chega. Cada etapa ajuda a reconhecer o que já sustenta o negócio, decidir o que precisa ganhar forma e construir um próximo passo possível.</p></div></section><section class="method-journey method-journey-page">${methodGroups.map(g=>`<article class="journey-step"><div class="journey-heading"><small>${g[0]}</small><span>${g[1]}</span></div><h2>${g[2]}</h2><p>${g[3]}</p><div class="journey-pairs">${g[4].map(id=>{const x=method.find(m=>m[0]===id);return `<div><span class="method-icon">${methodIcons[id]}</span><b>${x[1]}</b><p>${x[2]}</p></div>`}).join('')}</div></article>`).join('')}</section><p class="method-closing">O resultado não é uma presença inventada. É uma presença capaz de expressar, com clareza, o valor que já existe no seu trabalho.</p>${finalCta()}`,
  '/sobre': () => intro('SOBRE O ESTÚDIO','Estratégia que começa pela pessoa e chega à presença.','A Crie SeUniverso é um estúdio de arquitetura de posicionamento e presença digital para negócios que precisam ser compreendidos com mais clareza.') + `<section class="section about-section"><div class="about-photo-panel">${image('edson-novo.jpeg','Edson Lima em ambiente de trabalho','portrait-image')}</div><div class="about-copy"><p class="eyebrow">EDSON LIMA</p><h2>Antes de construir presença, é preciso saber escutar um negócio.</h2><p>A Crie SeUniverso é conduzida por Edson Lima, com mais de 25 anos de experiência em gestão, atendimento e vendas em diferentes ramos. Esse percurso ajuda a fazer perguntas mais úteis, reconhecer o que sustenta uma oferta e entender também quem está do outro lado da decisão.</p><p>Edson também tem cinco anos de experiência em atendimentos com terapias integrativas. Esse repertório traz familiaridade com a linguagem, os cuidados e os desafios de comunicar esse tipo de trabalho com clareza, responsabilidade e sem promessas que não cabem na prática.</p><p>O objetivo não é criar uma identidade artificial. É organizar o que já existe no trabalho para que a presença digital expresse isso com verdade, direção e contexto.</p></div></section>${finalCta()}`,
  '/contato': () => intro('CONTATO','Vamos olhar para o que o seu negócio já tem e ainda não está conseguindo mostrar?','Uma conversa inicial para entender o momento do seu negócio, o que já está claro e o que ainda precisa ganhar forma.') + `<section class="contact-action"><h2>O próximo passo pode ser simples.</h2><p>Conte um pouco sobre o seu trabalho, o que você oferece e onde sente que a comunicação ainda não acompanha o valor do negócio.</p>${cta('Conversar sobre o seu momento')}<p>Essa conversa ajuda a avaliar se o Site Estratégico faz sentido agora.</p></section>`
};
pages['/'] = homePage;
function finalCta(){return `<section class="final-cta">${image('cta-novo.jpeg','Edson Lima em seu estúdio, em frente à mesa de trabalho','cta-image')}<div class="cta-content"><p class="eyebrow">PRÓXIMO PASSO</p><h2>Seu trabalho não precisa de uma versão inventada. Precisa de uma forma clara de ser compreendido e escolhido.</h2>${cta('Conversar sobre meu posicionamento')}<p class="cta-microcopy">Uma conversa para entender o que já existe, o que está disperso e se o Mapa de Posicionamento faz sentido para o seu momento.</p></div></section>`}
const routeTitles = {
  '/': 'Crie SeUniverso | Mapa de Posicionamento e Site Estratégico',
  '/sites-estrategicos': 'Site Estratégico | Crie SeUniverso',
  '/como-funciona': 'Como funciona | Crie SeUniverso',
  '/sobre': 'Sobre a Crie SeUniverso | Edson Lima',
  '/contato': 'Contato — Crie SeUniverso'
};
const menuToggle = document.querySelector('.menu-toggle');
const nav = document.querySelector('nav');
const main = document.querySelector('main');
const homeLink = document.querySelector('.header-brand');

function closeMenu(){
  nav.classList.remove('open');
  menuToggle.setAttribute('aria-expanded','false');
  menuToggle.setAttribute('aria-label','Abrir menu de navegação');
}

function render(){
  const legacyRoute = location.hash.slice(1);
  if (legacyRoute && routePaths[legacyRoute]) {
    location.replace(routePaths[legacyRoute]);
    return;
  }
  const requestedRoute = location.pathname.replace(/\/$/, '') || '/';
  const route = pages[requestedRoute] ? requestedRoute : '/';
  if (requestedRoute !== route) history.replaceState(null, '', '/');
  main.innerHTML = pages[route]();
  document.querySelectorAll('[data-wa]').forEach(a=>a.href=whatsapp);
  document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===routePaths[route]));
  document.title = routeTitles[route];
  closeMenu();
  window.scrollTo(0,0);
  requestAnimationFrame(()=>main.focus({preventScroll:true}));
}

menuToggle.addEventListener('click',e=>{
  const expanded = e.currentTarget.getAttribute('aria-expanded') === 'true';
  e.currentTarget.setAttribute('aria-expanded',String(!expanded));
  e.currentTarget.setAttribute('aria-label',expanded ? 'Abrir menu de navegação' : 'Fechar menu de navegação');
  nav.classList.toggle('open',!expanded);
});
homeLink.addEventListener('click',e=>{
  e.preventDefault();
  closeMenu();
  if(location.pathname !== '/') location.assign('/');
  else render();
});
nav.addEventListener('click',closeMenu);
document.querySelector('#year').textContent = new Date().getFullYear();
render();
